global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'neo4j'
    metrics_path: /metrics
    static_configs:
      - targets: ['neo4j:2004']
  - job_name: 'mock-services'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'gateway:8000'
          - 'orchestrator:8001'
          - 'payments:8002'
          - 'inventory:8003'
          - 'recommendation:8004'
          - 'db:8005'
