[credentials]
admin_user = "admin"
admin_pwd = "Delahrg12"
viewer_user = "viewer"
viewer_pwd = "Delahrg12"

[bootstrap]
authorized_keys = "changeme-bootstrap-key"

[neo4j]
uri = "bolt://neo4j.dev.sentrinode.net:7687"
user = "neo4j"
password = "Delahrg12"

[webhooks]
alert_url = "https://hooks.slack.com/services/T000/B000/XXXX"
