[credentials]
admin_user = ""
admin_pwd = ""
viewer_user = ""
viewer_pwd = ""

[bootstrap]
authorized_keys = "changeme-bootstrap-key"

[neo4j]
uri = "bolt://sentri-db:7687"
user = "neo4j"
password = "Delahrg12"

[webhooks]
alert_url = "https://hooks.slack.com/services/T000/B000/XXXX"
